#!/bin/bash

killall test_service_server_cpp
killall test_service_client_cpp
killall test_pub_cpp
killall test_sub_cpp
killall test_tmsync_pub_cpp
killall test_tmsync_sub_cpp
killall dcos_param2_server_service
killall test_param2_client
